// Case rules: the conditions that decide when stages and tasks start, complete,
// or exit. These are what the case agent reads at run time.
//
// Transcribed from the storyboard's Studio "Rules" view (scene 10) plus the
// SDD's stage entry/exit tables. Scene 11 adds the two v2 rows: the recovery
// gate on Settlement & Closure, and the routing change that points the
// recovery-detected event at the new Subrogation & Recovery stage.

export type RuleScope = "Case" | "Stage" | "Sequential task" | "Event-driven task" | "Manually triggered";

export interface CaseRule {
  id: string;
  scope: RuleScope;
  element: string;
  rule: string;
  when: string;
  /** Guard expression. Empty when the rule fires unconditionally. */
  if?: string;
  then: string;
  /** Rules the coding agent generated rather than a reviewer authoring. */
  autoGenerated?: boolean;
  /** The reviewer this rule came out of, per storyboard scene 10. */
  authoredBy?: string;
  /** Case plan version this rule was introduced in. */
  since: "v1" | "v2";
}

export const CASE_RULES: CaseRule[] = [
  {
    id: "r01",
    scope: "Case",
    element: "Portal",
    rule: "Case entry",
    when: "Claim submitted",
    then: "Enter case",
    since: "v1",
  },
  {
    id: "r02",
    scope: "Stage",
    element: "Claim Intake & Registration",
    rule: "Enter case",
    when: "Case entered",
    then: "Enter Claim Intake & Registration",
    since: "v1",
  },
  {
    id: "r03",
    scope: "Sequential task",
    element: "Assemble medical evidence (Agent)",
    rule: "Task entry",
    when: "Stage entered",
    then: "Enter Assemble medical evidence",
    autoGenerated: true,
    since: "v1",
  },
  {
    id: "r04",
    scope: "Sequential task",
    element: "Classify injury severity (Human)",
    rule: "Task entry",
    when: "Upstream task completed",
    then: "Enter Classify injury severity",
    autoGenerated: true,
    since: "v1",
  },
  {
    id: "r05",
    scope: "Stage",
    element: "Claim Intake & Registration",
    rule: "Stage complete",
    when: "Required tasks completed",
    then: "Complete Claim Intake & Registration",
    since: "v1",
  },
  {
    id: "r06",
    scope: "Stage",
    element: "Medical Evidence & Quantum Decision",
    rule: "Stage complete",
    when: "Required tasks completed",
    then: "Complete Medical Evidence & Quantum Decision",
    since: "v1",
  },
  {
    id: "r07",
    scope: "Stage",
    element: "Medical Evidence & Quantum Decision",
    rule: "Liability ownership",
    when: "Stage entered",
    then: "Assign to Aldergate Claims Operations",
    authoredBy: "Priya Nakamura",
    since: "v1",
  },
  {
    id: "r08",
    scope: "Event-driven task",
    element: "Condition Deterioration & Re-assessment",
    rule: "Task entry",
    when: "New medical evidence uploaded",
    if: "assessedInjury !== admittedInjury",
    then: "Enter Condition Deterioration & Re-assessment",
    since: "v1",
  },
  {
    id: "r09",
    scope: "Stage",
    element: "Escalation & Authority Referral",
    rule: "Delegated authority",
    when: "Settlement figure compiled",
    if: "estimatedQuantum > officer.authorityLimit",
    then: "Refer to a manager for authorisation",
    authoredBy: "Priya Nakamura",
    since: "v1",
  },
  {
    id: "r10",
    scope: "Stage",
    element: "Settlement & Closure",
    rule: "Recovery gate",
    when: "Tasks completed: Third-party recovery screen",
    if: "recoveryCandidatesFound >= 1",
    then: "Enter Subrogation & Recovery",
    autoGenerated: true,
    authoredBy: "Bethany Okwuosa",
    since: "v2",
  },
  {
    id: "r11",
    scope: "Stage",
    element: "Settlement & Closure",
    rule: "Stage complete",
    when: "Required tasks completed",
    if: "recoveryReviewed === true",
    then: "Complete Settlement & Closure",
    since: "v2",
  },
  {
    id: "r12",
    scope: "Manually triggered",
    element: "Complaint & Ombudsman Referral",
    rule: "Entry rule 1",
    when: "Manual activation",
    then: "Enter Complaint & Ombudsman Referral",
    since: "v1",
  },
];

/** The v1 → v2 diff the coding agent applied, shown on the Case plans page. */
export const PLAN_CHANGELOG = {
  from: "v1",
  to: "v2",
  prompt:
    "Add a recovery gate before a claim can close, if the third-party recovery screen finds a candidate and it hasn't been reviewed.",
  changes: [
    { kind: "added" as const, text: "Stage added: Subrogation & Recovery (4 tasks)" },
    {
      kind: "updated" as const,
      text: 'Rule updated: Settlement & Closure now requires "recovery reviewed = true"',
    },
    { kind: "updated" as const, text: "Routing: recovery-detected event now targets the new stage" },
  ],
  summary: "3 changes · 1 stage, 1 rule, 1 route · case plan version 1 → 2",
  migrationNote: "Running claims can be migrated onto v2 without restarting.",
};
